version: 2

_environemnt:
    # WORKSPACE_PATH: &WORKSPACE_PATH /tmp/workspace
    PROJECT_PATH: &PROJECT_PATH /root/project
    environment: &environment
        # WORKSPACE_PATH: *WORKSPACE_PATH
        PROJECT_PATH: *PROJECT_PATH

_steps:
    # persist_build_to_workspace: &persist_build_to_workspace
    #     persist_to_workspace:
    #         root: *WORKSPACE_PATH
    #         paths:
    #             - build
    # attach_workspace: &attach_workspace
    #     attach_workspace:
    #         at: *WORKSPACE_PATH

jobs:
    upload_webpublic:
        docker:
            - image: mesosphere/aws-cli:1.14.5
        environment:
            <<: *environment
        steps:
            - checkout
            - run:
                name: TODO
                command: |
                    ./aws.sh


workflows:
    version: 2
    on_push:
        jobs:
            - upload_webpublic
